/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dnd1;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author shubham
 */
public class addmoviepanel extends javax.swing.JPanel {
   ImageIcon bg;
    Image img;
    
    public addmoviepanel() {
        initComponents();
        bg = new ImageIcon("its.jpg");
        img = bg.getImage();
        
        Dimension d = new Dimension(img.getWidth(null), img.getHeight(null));
        setPreferredSize(d);
        setMinimumSize(d);
        setMaximumSize(d);
        setSize(d);
    }
    @Override
    public void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D gg = (Graphics2D) g;
    gg.drawImage(img, 0, 0, this);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setBackground(new java.awt.Color(255, 255, 51));
        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jTextField4.setOpaque(false);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Course");

        jLabel2.setText("Name : ");

        jLabel1.setText("Reg. No");

        jLabel4.setText("School");

        jLabel3.setText("Addmission Date");

        jLabel6.setText("Student Name : ");

        jButton1.setText("Attach Image ");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 3, 14)); // NOI18N
        jLabel10.setText("Enter Student Details : ");

        jLabel12.setText("Background : ");

        jButton3.setText("Attach Image");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("* Compulsory");

        jLabel14.setText("* Compulsory");

        jLabel15.setText("* Compulsory");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addContainerGap(123, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addComponent(jLabel13))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(63, 63, 63)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
            JFileChooser jf = new JFileChooser();
		jf.showOpenDialog(null);
		File f = jf.getSelectedFile();
				
		try {
			
			
			FileInputStream fis = new FileInputStream(f);
			ByteArrayOutputStream bos = new ByteArrayOutputStream();
			byte[] by = new byte[1024];
			
			for (int readnum; (readnum = fis.read(by) ) != -1; ) {
				bos.write(by, 0, readnum);
				
			}
			
			image = bos.toByteArray();
                        /// imagechange = true;
		} catch (Exception ex) {
			System.out.println(ex);
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                
        
            JFileChooser jf = new JFileChooser();
		jf.showOpenDialog(null);
		File f = jf.getSelectedFile();
				
		try {
			
			
			FileInputStream fis = new FileInputStream(f);
			ByteArrayOutputStream bos = new ByteArrayOutputStream();
			byte[] by = new byte[1024];
			
			for (int readnum; (readnum = fis.read(by) ) != -1; ) {
				bos.write(by, 0, readnum);
				
			}
			
			image2 = bos.toByteArray();
                        /// imagechange = true;
		} catch (Exception ex) {
			System.out.println(ex);
		}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String [] s = new String[10];
        s[0] = jTextField1.getText();//
        int mid = Integer.parseInt(s[0]);
        s[1] = jTextField2.getText();
        Date d = new Date();
        d = jDateChooser1.getDate();
        String query;
        System.out.println(d);

        DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        String dateString = dateFormat.format(d);
        dateString = dateString.toLowerCase();

        System.out.println(dateString);

        s[3] = jTextField4.getText();//
        int np = Integer.parseInt(s[3]);
        s[4] = jTextField5.getText();//
        int pm = Integer.parseInt(s[4]);

        globalclass.s1 = s[1];

        if(jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals("") || jTextField4.getText().equals("") || jTextField5.getText().equals("") || jTextField6.getText().equals("") || jTextField7.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter All Fields");
        } else {

            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
            } catch(Exception e) {
                System.out.println("Oops! Can't find classoracle.jdbc.driver.OracleDriver");
            }
            try {
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "oracle");
                Statement stmt = conn.createStatement();

                query = "delete from movieTable where id =" + s[0];
                System.out.println(query);
                stmt.executeQuery(query);
                query = "Insert into movieTable values (? , ?, ? , ?, ?, ?, ?, ?, ?,?,?)";

                String ss = image.toString();

                PreparedStatement pst = conn.prepareStatement(query);

                System.out.println(mid + " = mid" + " np = " + np + " pm = " + pm + "  "+ image + image2);

                pst.setInt(1, Integer.parseInt(jTextField1.getText()));
                pst.setString(2, jTextField2.getText());
                pst.setInt(4, Integer.parseInt(jTextField4.getText()));
                pst.setInt(5,Integer.parseInt(jTextField5.getText()));
                pst.setString(6, "A");
                pst.setBytes(7, image);
                pst.setString(3, new SimpleDateFormat("dd-MMM-yyyy").format(jDateChooser1.getDate()));
                pst.setString(8, jTextField3.getText());
                pst.setString(9, jTextField6.getText());
                pst.setString(10, jTextField7.getText());
                pst.setBytes(11, image2);

                System.out.println(query);

                pst.execute();

                pst.setInt(1, Integer.parseInt(jTextField1.getText()));
                pst.setString(2, jTextField2.getText());
                pst.setInt(4, Integer.parseInt(jTextField4.getText()));
                pst.setInt(5,Integer.parseInt(jTextField5.getText()));
                pst.setString(6, "B");
                pst.setBytes(7, image);
                pst.setString(3, new SimpleDateFormat("dd-MMM-yyyy").format(jDateChooser1.getDate()));
                pst.setString(8, jTextField3.getText());
                pst.setString(9, jTextField6.getText());
                pst.setString(10, jTextField7.getText());
                pst.setBytes(11, image2);

                pst.execute();
                System.out.println(query);

                System.out.println("here");

                pst.setInt(1, Integer.parseInt(jTextField1.getText()));
                pst.setString(2, jTextField2.getText());
                pst.setInt(4, Integer.parseInt(jTextField4.getText()));
                pst.setInt(5,Integer.parseInt(jTextField5.getText()));
                pst.setString(6, "C");
                pst.setBytes(7, image);
                pst.setString(3, new SimpleDateFormat("dd-MMM-yyyy").format(jDateChooser1.getDate()));
                pst.setString(8, jTextField3.getText());
                pst.setString(9, jTextField6.getText());
                pst.setString(10, jTextField7.getText());
                pst.setBytes(11, image2);

                pst.execute();
                System.out.println(query);

                pst.setInt(1, Integer.parseInt(jTextField1.getText()));
                pst.setString(2, jTextField2.getText());
                pst.setInt(4, Integer.parseInt(jTextField4.getText()));
                pst.setInt(5,Integer.parseInt(jTextField5.getText()));
                pst.setString(6, "D");
                pst.setBytes(7, image);
                pst.setString(3, new SimpleDateFormat("dd-MMM-yyyy").format(jDateChooser1.getDate()));
                pst.setString(8, jTextField3.getText());
                pst.setString(9, jTextField6.getText());
                pst.setString(10, jTextField7.getText());
                pst.setBytes(11, image2);

                pst.execute();
                System.out.println(query);

                JOptionPane.showMessageDialog(null, "Successfully Inserted 1 Movie ");

            } catch (SQLException e) {
                System.out.println("Cannot Connect");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    byte [] image = null;
    byte [] image2 = null;
    boolean imagechange;

}
