/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dnd1;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author haris khan
 */
public class bookinghistorypanel extends javax.swing.JPanel {

    /**
     * Creates new form bookinghistorypanel
     */
    
   
    
    

    
    public bookinghistorypanel() {
        initComponents();
        
    //    filltable();
         try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                } catch(Exception e) {
                    System.out.println("Oops! Can't find classoracle.jdbc.driver.OracleDriver");
                }
                try {
                   Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "oracle");
                    java.sql.Statement stmt = conn.createStatement();
                
                    String query = "Select * from book where username = '" + globalclass.username + "'";
               
                    System.out.println(query);
                
                    ResultSet rs = stmt.executeQuery(query);
                    DefaultTableModel model = new DefaultTableModel(
                    new Object [][] {},
                    new String [] {"User Name ", "Movie ID", "Seats", "Class","Amount"}
                    ) {
                    boolean[] canEdit = new boolean [] {false, false, false, false, false};
                    @Override
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                    }
                    };
                    jTable1.setModel(model);
                    
                   while(rs.next()) {
                    model.addRow(new Object[] {rs.getString(1), rs.getInt(2),rs.getInt(3), rs.getString(4), rs.getInt(5)});
                    }  
                } catch (SQLException e) {
                    System.out.println("Cannot Connect");
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setForeground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Movie Id ", "Movie Name", "Date Of Booking", "Seats", "Class ", "Amount "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 125, 612, 89));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Booking History :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 64, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("To Cancel : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 299, -1, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Movie Id : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 349, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 346, 37, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cancel my.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 121, 23));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Your Password : ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 349, -1, -1));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 346, 118, -1));

        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("ONLY 80% OF THE NET AMOUNT WILL BE REFUNDED.");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 318, 19));

        jRadioButton1.setForeground(new java.awt.Color(255, 255, 102));
        jRadioButton1.setText("I Agree");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, -1, -1));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forward.gif"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 27));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        
        String mid = jTextField1.getText();
        String pass = jPasswordField1.getText();
        
        System.out.println(globalclass.password);
        
       
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jPasswordField1.getText().equals(globalclass.password)) {
            if(jRadioButton1.isSelected()){
                try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                } catch(Exception e) {
                    System.out.println("Oops! Can't find classoracle.jdbc.driver.OracleDriver");
                }
                try {
                   Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "oracle");
                    java.sql.Statement stmt = conn.createStatement();
                
                    String query = "Select amount from book where mid = " + jTextField1.getText() + " and username = '" + globalclass.username + "'";
               
                    System.out.println(query);
                    ResultSet rs = stmt.executeQuery(query);
                    if(rs.next()) {
                        String s = "" + (0.8 * rs.getInt(1));
                     //   update account set bal = 1000 where cardnum = (select cardnum from book where username = 'shu' and mid = 3)
                        query = "update account set bal = " + s + " where cardnum =  ( select cardnum from book where username = '" + globalclass.username + "' and mid = " + jTextField1.getText() + " )";
                        System.out.println(query);
                        rs =  stmt.executeQuery(query);
                        JOptionPane.showMessageDialog(null, "Successfully Refunded " + s + " to your Account" );
                       // delete from book where username = 'shu' and mid = 3
                        query = "delete from book where username = '" + globalclass.username + "' and mid = " + jTextField1.getText();         
                         rs =  stmt.executeQuery(query);
                        new homepage().setVisible(true);
                    }
                 
                } catch (SQLException e) {
                    System.out.println("Cannot Connect");
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Please Agree to the Terms And Condition of REFUND");
            }
        } else {
            if(jPasswordField1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter Password");
            } else {
            JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        }
     
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        this.setVisible(false);
        new homepage().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
