/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dnd1;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
//import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author shubham
 */

/*class ImagePanel1 extends JPanel {

    private BufferedImage image;

    public ImagePanel1() {
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        
         Image bg = new ImageIcon("bk.gif").getImage();
         g.drawImage(bg, 0, 0, getWidth(), getHeight(), this);
            
        
        
        Image i = new ImageIcon("dd.gif").getImage();
        g2d.drawImage(i, 9, 29, this);         
    }

}




class drawpanel extends JPanel {

    //private BufferedImage image;

    public drawpanel() {
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        
     //    Image bg = new ImageIcon("bk.gif").getImage();
     //    g.drawImage(bg, 0, 0, getWidth(), getHeight(), this);
            
        
        
        Image i = new ImageIcon("dd.gif").getImage();
        g2d.drawImage(i, 9, 29, this);         
    }

}
*/
public class homepanel extends javax.swing.JPanel {

    /**
     * Creates new form homepanel
     */
     ImageIcon bg;
    Image img;
    
    public homepanel() {
        initComponents();
        bg = new ImageIcon("it6.jpg");
        img = bg.getImage();
        
        Dimension d = new Dimension(img.getWidth(null), img.getHeight(null));
        setPreferredSize(d);
        setMinimumSize(d);
        setMaximumSize(d);
        setSize(d);
    }
    @Override
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        Graphics2D gg = (Graphics2D) g;
        gg.drawImage(img, 0, 0, this);
        gifp np = new gifp();
        add(np);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        movingimagepanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 0, 102));

        jButton1.setText("jButton1");

        movingimagepanel.setBackground(new java.awt.Color(244, 192, 174));
        movingimagepanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        javax.swing.GroupLayout movingimagepanelLayout = new javax.swing.GroupLayout(movingimagepanel);
        movingimagepanel.setLayout(movingimagepanelLayout);
        movingimagepanelLayout.setHorizontalGroup(
            movingimagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        movingimagepanelLayout.setVerticalGroup(
            movingimagepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(775, 775, 775)
                .addComponent(movingimagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(521, 521, 521))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movingimagepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(273, 273, 273)
                .addComponent(jButton1)
                .addContainerGap(292, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel movingimagepanel;
    // End of variables declaration//GEN-END:variables
}
