/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dnd1;

/**
 *
 * @author shubham
 */
public class movienew extends javax.swing.JPanel {

    /**
     * Creates new form movienew
     */
    public movienew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            bookingpanel2 = new dnd1.bookingpanel();
        } catch (java.sql.SQLException e1) {
            e1.printStackTrace();
        }

        bookingpanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingpanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookingpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1346, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookingpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookingpanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingpanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingpanel2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dnd1.bookingpanel bookingpanel2;
    // End of variables declaration//GEN-END:variables
}
